# Generated by Django 2.2.7 on 2020-05-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'information',
                'managed': False,
            },
        ),
    ]
