# Generated by Django 2.2.7 on 2020-07-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={},
        ),
    ]
